/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sabi_sample_gnu_coreutils_lib_OsDaxConn */

#ifndef _Included_sabi_sample_gnu_coreutils_lib_OsDaxConn
#define _Included_sabi_sample_gnu_coreutils_lib_OsDaxConn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sabi_sample_gnu_coreutils_lib_OsDaxConn
 * Method:    getEuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sabi_sample_gnu_coreutils_lib_OsDaxConn_getEuid
  (JNIEnv *, jobject);

/*
 * Class:     sabi_sample_gnu_coreutils_lib_OsDaxConn
 * Method:    getPwdByUid
 * Signature: (ILsabi/sample/gnu/coreutils/lib/Passwd;)I
 */
JNIEXPORT jint JNICALL Java_sabi_sample_gnu_coreutils_lib_OsDaxConn_getPwdByUid
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
